/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package titanic.gui.support;

import javax.swing.JButton;

/**
 *
 * @author Menes
 */
public class MeetingPanel extends javax.swing.JPanel {

    /**
     * Creates new form MeetingPanel
     */
    public MeetingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        startAudioMeetingButton = new javax.swing.JButton();
        startVideoCallMeetingButton = new javax.swing.JButton();
        startMeetingButton = new javax.swing.JButton();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        setLayout(layout);

        startAudioMeetingButton.setText("Empezar Grabando Audio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(startAudioMeetingButton, gridBagConstraints);

        startVideoCallMeetingButton.setText("Empezar con Video Llamada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        add(startVideoCallMeetingButton, gridBagConstraints);

        startMeetingButton.setText("Empezar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        add(startMeetingButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton startAudioMeetingButton;
    private javax.swing.JButton startMeetingButton;
    private javax.swing.JButton startVideoCallMeetingButton;
    // End of variables declaration//GEN-END:variables

    public JButton getStartAudioMeetingButton() {
        return startAudioMeetingButton;
    }

    public void setStartAudioMeetingButton(JButton startAudioMeetingButton) {
        this.startAudioMeetingButton = startAudioMeetingButton;
    }

    public JButton getStartMeetingButton() {
        return startMeetingButton;
    }

    public void setStartMeetingButton(JButton startMeetingButton) {
        this.startMeetingButton = startMeetingButton;
    }

    public JButton getStartVideoCallMeetingButton() {
        return startVideoCallMeetingButton;
    }

    public void setStartVideoCallMeetingButton(JButton startVideoCallMeetingButton) {
        this.startVideoCallMeetingButton = startVideoCallMeetingButton;
    }
}
