/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package titanic.gui.support;

import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Menes
 */
public class SupportPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupportPanel
     */
    public SupportPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        meetingButton = new javax.swing.JButton();
        whiteboardButton = new javax.swing.JButton();
        returnBackLabel = new javax.swing.JLabel();
        scheduleButton = new javax.swing.JButton();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        setLayout(layout);

        meetingButton.setText("Reunion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 26;
        add(meetingButton, gridBagConstraints);

        whiteboardButton.setText("Whiteboard");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 26;
        add(whiteboardButton, gridBagConstraints);

        returnBackLabel.setText("<- Back");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 40;
        gridBagConstraints.gridwidth = 7;
        add(returnBackLabel, gridBagConstraints);

        scheduleButton.setText("Cronograma");
        scheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 26;
        add(scheduleButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void scheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleButtonActionPerformed
        String command =  "cmd /C start winproj";
        try {
            Process process = Runtime.getRuntime().exec(command);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "MS Project no se pudo iniciar",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_scheduleButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton meetingButton;
    private javax.swing.JLabel returnBackLabel;
    private javax.swing.JButton scheduleButton;
    private javax.swing.JButton whiteboardButton;
    // End of variables declaration//GEN-END:variables

    public JButton getMeetingButton() {
        return meetingButton;
    }

    public void setMeetingButton(JButton meetingButton) {
        this.meetingButton = meetingButton;
    }

    public JButton getWhiteboardButton() {
        return whiteboardButton;
    }

    public void setWhiteboardButton(JButton whiteboardButton) {
        this.whiteboardButton = whiteboardButton;
    }

    public JLabel getReturnBackLabel() {
        return returnBackLabel;
    }

    public void setReturnBackLabel(JLabel returnBackLabel) {
        this.returnBackLabel = returnBackLabel;
    }
    
}
