/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package titanic.gui.support;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.InputEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Menes
 */
public class WhiteboardPanel extends javax.swing.JPanel {
        
    /**
     * Creates new form WhiteboardPanel
     */
    public WhiteboardPanel() {
        initComponents();
        setWhiteboardBehavior();
    }

    private void setWhiteboardBehavior() {
        
        jPanel1.addMouseMotionListener(new MouseMotionListener() {
            @Override
            public void mouseDragged(MouseEvent e) {
                Graphics g = jPanel1.getGraphics();
                if ((e.getModifiers() & InputEvent.BUTTON1_MASK) != 0) {                    
                    g.setColor(Color.black);
                    g.fillOval(e.getX() - 5, e.getY() - 5, 10, 10);
                    jPanel1.paintComponents(g);
                }
                if ((e.getModifiers() & InputEvent.BUTTON3_MASK) != 0) {
                    jPanel1.updateUI();
                }
            }
            @Override
            public void mouseMoved(MouseEvent e) {
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        addPostItButton = new javax.swing.JButton();
        addImageButton = new javax.swing.JButton();
        returnBackLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        setLayout(layout);

        addPostItButton.setText("+PostIt");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 4;
        add(addPostItButton, gridBagConstraints);

        addImageButton.setText("+Imagen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 6;
        add(addImageButton, gridBagConstraints);

        returnBackLabel.setText("<- Back");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 8;
        add(returnBackLabel, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Whiteboard"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addImageButton;
    private javax.swing.JButton addPostItButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel returnBackLabel;
    // End of variables declaration//GEN-END:variables

    public JButton getAddImageButton() {
        return addImageButton;
    }

    public void setAddImageButton(JButton addImageButton) {
        this.addImageButton = addImageButton;
    }

    public JButton getAddPostItButton() {
        return addPostItButton;
    }

    public void setAddPostItButton(JButton addPostItButton) {
        this.addPostItButton = addPostItButton;
    }

    public JLabel getReturnBackLabel() {
        return returnBackLabel;
    }

    public void setReturnBackLabel(JLabel returnBackLabel) {
        this.returnBackLabel = returnBackLabel;
    }
}
