/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package titanic.gui.needsfinding;

import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Menes
 */
public class DrawPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrawPanel
     */
    public DrawPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        msPaintButton = new javax.swing.JButton();
        autoCadButton = new javax.swing.JButton();
        solidWorksButton = new javax.swing.JButton();
        creoPtcButton = new javax.swing.JButton();
        sketchBookButton = new javax.swing.JButton();
        returnBackLabel = new javax.swing.JLabel();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        setLayout(layout);

        msPaintButton.setText("MS Paint");
        msPaintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msPaintButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(msPaintButton, gridBagConstraints);

        autoCadButton.setText("AutoCAD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        add(autoCadButton, gridBagConstraints);

        solidWorksButton.setText("SolidWorks");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        add(solidWorksButton, gridBagConstraints);

        creoPtcButton.setText("Creo PTC");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(creoPtcButton, gridBagConstraints);

        sketchBookButton.setText("Sketch Book");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        add(sketchBookButton, gridBagConstraints);

        returnBackLabel.setText("<- Back");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridwidth = 7;
        add(returnBackLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void msPaintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msPaintButtonActionPerformed
        String command =  "cmd /C start mspaint";
        try {
            Process process = Runtime.getRuntime().exec(command);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "MS Paint no se pudo iniciar",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_msPaintButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autoCadButton;
    private javax.swing.JButton creoPtcButton;
    private javax.swing.JButton msPaintButton;
    private javax.swing.JLabel returnBackLabel;
    private javax.swing.JButton sketchBookButton;
    private javax.swing.JButton solidWorksButton;
    // End of variables declaration//GEN-END:variables

    public JButton getAutoCadButton() {
        return autoCadButton;
    }

    public void setAutoCadButton(JButton autoCadButton) {
        this.autoCadButton = autoCadButton;
    }

    public JButton getCreoPtcButton() {
        return creoPtcButton;
    }

    public void setCreoPtcButton(JButton creoPtcButton) {
        this.creoPtcButton = creoPtcButton;
    }

    public JButton getMsPaintButton() {
        return msPaintButton;
    }

    public void setMsPaintButton(JButton msPaintButton) {
        this.msPaintButton = msPaintButton;
    }

    public JLabel getReturnBackLabel() {
        return returnBackLabel;
    }

    public void setReturnBackLabel(JLabel returnBackLabel) {
        this.returnBackLabel = returnBackLabel;
    }

    public JButton getSketchBookButton() {
        return sketchBookButton;
    }

    public void setSketchBookButton(JButton sketchBookButton) {
        this.sketchBookButton = sketchBookButton;
    }

    public JButton getSolidWorksButton() {
        return solidWorksButton;
    }

    public void setSolidWorksButton(JButton solidWorksButton) {
        this.solidWorksButton = solidWorksButton;
    }
}
