/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package titanic.gui.needsfinding;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Menes
 */
public class NeedsFindingPanel extends javax.swing.JPanel {

    /**
     * Creates new form NeedsFindingPanel
     */
    public NeedsFindingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        generateButton = new javax.swing.JButton();
        writeButton = new javax.swing.JButton();
        drawButton = new javax.swing.JButton();
        returnBackLabel = new javax.swing.JLabel();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        setLayout(layout);

        generateButton.setText("Generar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(generateButton, gridBagConstraints);

        writeButton.setText("Escribir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(writeButton, gridBagConstraints);

        drawButton.setText("Dibujar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        add(drawButton, gridBagConstraints);

        returnBackLabel.setText("<- Back");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 5;
        add(returnBackLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton drawButton;
    private javax.swing.JButton generateButton;
    private javax.swing.JLabel returnBackLabel;
    private javax.swing.JButton writeButton;
    // End of variables declaration//GEN-END:variables

    public JButton getDrawButton() {
        return drawButton;
    }

    public void setDrawButton(JButton drawButton) {
        this.drawButton = drawButton;
    }

    public JButton getGenerateButton() {
        return generateButton;
    }

    public void setGenerateButton(JButton generateButton) {
        this.generateButton = generateButton;
    }

    public JLabel getReturnBackLabel() {
        return returnBackLabel;
    }

    public void setReturnBackLabel(JLabel returnBackLabel) {
        this.returnBackLabel = returnBackLabel;
    }

    public JButton getWriteButton() {
        return writeButton;
    }

    public void setWriteButton(JButton writeButton) {
        this.writeButton = writeButton;
    }
}
