/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package titanic.gui.needsfinding;

import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Menes
 */
public class WritePanel extends javax.swing.JPanel {

    /**
     * Creates new form WritePanel
     */
    public WritePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        msWordButton = new javax.swing.JButton();
        msPowerPntButton = new javax.swing.JButton();
        msExcelButton = new javax.swing.JButton();
        returnBackLabel = new javax.swing.JLabel();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        setLayout(layout);

        msWordButton.setText("MS Word");
        msWordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msWordButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(msWordButton, gridBagConstraints);

        msPowerPntButton.setText("MS PowerPoint");
        msPowerPntButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msPowerPntButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(msPowerPntButton, gridBagConstraints);

        msExcelButton.setText("MS Excel");
        msExcelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msExcelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        add(msExcelButton, gridBagConstraints);

        returnBackLabel.setText("<- Back");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 5;
        add(returnBackLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void msWordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msWordButtonActionPerformed
        String command =  "cmd /C start winword";
        try {
            Process process = Runtime.getRuntime().exec(command);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "MS Word no se pudo iniciar",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_msWordButtonActionPerformed

    private void msPowerPntButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msPowerPntButtonActionPerformed
        String command =  "cmd /C start powerpnt";
        try {
            Process process = Runtime.getRuntime().exec(command);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "MS PowerPoint no se pudo iniciar",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_msPowerPntButtonActionPerformed

    private void msExcelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msExcelButtonActionPerformed
        String command =  "cmd /C start excel";
        try {
            Process process = Runtime.getRuntime().exec(command);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "MS Excel no se pudo iniciar",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_msExcelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton msExcelButton;
    private javax.swing.JButton msPowerPntButton;
    private javax.swing.JButton msWordButton;
    private javax.swing.JLabel returnBackLabel;
    // End of variables declaration//GEN-END:variables

    public JButton getMsExcelButton() {
        return msExcelButton;
    }

    public void setMsExcelButton(JButton msExcelButton) {
        this.msExcelButton = msExcelButton;
    }

    public JButton getMsPowerPntButton() {
        return msPowerPntButton;
    }

    public void setMsPowerPntButton(JButton msPowerPntButton) {
        this.msPowerPntButton = msPowerPntButton;
    }

    public JButton getMsWordButton() {
        return msWordButton;
    }

    public void setMsWordButton(JButton msWordButton) {
        this.msWordButton = msWordButton;
    }

    public JLabel getReturnBackLabel() {
        return returnBackLabel;
    }

    public void setReturnBackLabel(JLabel returnBackLabel) {
        this.returnBackLabel = returnBackLabel;
    }
}
