/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package titanic.gui;

import ch.randelshofer.quaqua.*;
import java.awt.Frame;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import titanic.utilities.VerticalLabelUI;

/**
 *
 * @author Menes
 */
public class MainTitanicWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainTitanicWindow
     */
    public MainTitanicWindow() {
        setNimbus("Quaqua");
        initComponents();
        setJLabelVertical();
        setFullScreen();
    }
    
    private void setFullScreen(){
        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        try{
            gd.setFullScreenWindow(this);
        }catch( Exception e ){
            System.out.println( e.getCause() + ": " + e.getMessage() );
        }
    }
    
    private void setNimbus(String option) {
        // Code from Oracle Docs
        try {
            if (option.equals("Nimbus")) {
                for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                    if (option.equals(info.getName())) {
                        UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } else if (option.equals("Quaqua")) {
                UIManager.setLookAndFeel( ch.randelshofer.quaqua.QuaquaManager.getLookAndFeel() );
            }
        } catch (Exception e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
            System.out.println(e.getMessage());
        }
    }

    private void setJLabelVertical(){
        this.currentCompLabel.setUI( new VerticalLabelUI() );
        currentCompLabel.setText("Inicio");
    }

    /*
     * Getters & Setters
     */
    
    public JLabel getCurrentCompLabel() {
        return currentCompLabel;
    }

    public void setCurrentCompLabel(JLabel currentCompLabel) {
        this.currentCompLabel = currentCompLabel;
    }

    public JPanel getCurrentCompPanel() {
        return currentCompPanel;
    }

    public void setCurrentCompPanel(JPanel currentCompPanel) {
        this.currentCompPanel = currentCompPanel;
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public void setMainPanel(JPanel mainPanel) {
        this.mainPanel = mainPanel;
    }

    public JPanel getTopBarPanel() {
        return topBarPanel;
    }

    public void setTopBarPanel(JPanel topBarPanel) {
        this.topBarPanel = topBarPanel;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        currentCompPanel = new javax.swing.JPanel();
        currentCompLabel = new javax.swing.JLabel();
        topBarPanel = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        minimizeButton = new javax.swing.JButton();
        questionButton = new javax.swing.JButton();
        infoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);

        mainPanel.setLayout(new java.awt.BorderLayout());

        currentCompLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentCompLabel.setText("{}");
        currentCompLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout currentCompPanelLayout = new javax.swing.GroupLayout(currentCompPanel);
        currentCompPanel.setLayout(currentCompPanelLayout);
        currentCompPanelLayout.setHorizontalGroup(
            currentCompPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentCompLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        currentCompPanelLayout.setVerticalGroup(
            currentCompPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentCompLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        mainPanel.add(currentCompPanel, java.awt.BorderLayout.LINE_START);

        exitButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        exitButton.setText("Close");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        minimizeButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        minimizeButton.setText("Minimize");
        minimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeButtonActionPerformed(evt);
            }
        });

        questionButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        questionButton.setText("¿?");

        infoButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        infoButton.setText("Info");

        javax.swing.GroupLayout topBarPanelLayout = new javax.swing.GroupLayout(topBarPanel);
        topBarPanel.setLayout(topBarPanelLayout);
        topBarPanelLayout.setHorizontalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanelLayout.createSequentialGroup()
                .addComponent(exitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minimizeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(questionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoButton))
        );
        topBarPanelLayout.setVerticalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(exitButton)
                .addComponent(minimizeButton)
                .addComponent(infoButton)
                .addComponent(questionButton))
        );

        mainPanel.add(topBarPanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void minimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeButtonActionPerformed
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentCompLabel;
    private javax.swing.JPanel currentCompPanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton infoButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton minimizeButton;
    private javax.swing.JButton questionButton;
    private javax.swing.JPanel topBarPanel;
    // End of variables declaration//GEN-END:variables
}
