/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package titanic.gui;

import javax.swing.JButton;

/**
 *
 * @author Menes
 */
public class SectionPanel extends javax.swing.JPanel {

    /**
     * Creates new form SectionPanel
     */
    public SectionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        supportButton = new javax.swing.JButton();
        needsFindingButton = new javax.swing.JButton();
        conceptDesignButton = new javax.swing.JButton();
        detailDesignButton = new javax.swing.JButton();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        setLayout(layout);

        supportButton.setText("Soporte");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(supportButton, gridBagConstraints);

        needsFindingButton.setText("Busqueda de Necesidades");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        add(needsFindingButton, gridBagConstraints);

        conceptDesignButton.setText("Diseño Conceptual");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(conceptDesignButton, gridBagConstraints);

        detailDesignButton.setText("Diseño de Detalle");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        add(detailDesignButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conceptDesignButton;
    private javax.swing.JButton detailDesignButton;
    private javax.swing.JButton needsFindingButton;
    private javax.swing.JButton supportButton;
    // End of variables declaration//GEN-END:variables

    public JButton getConceptDesignButton() {
        return conceptDesignButton;
    }

    public void setConceptDesignButton(JButton conceptDesignButton) {
        this.conceptDesignButton = conceptDesignButton;
    }

    public JButton getDetailDesignButton() {
        return detailDesignButton;
    }

    public void setDetailDesignButton(JButton detailDesignButton) {
        this.detailDesignButton = detailDesignButton;
    }

    public JButton getNeedsFindingButton() {
        return needsFindingButton;
    }

    public void setNeedsFindingButton(JButton needsFindingButton) {
        this.needsFindingButton = needsFindingButton;
    }

    public JButton getSupportButton() {
        return supportButton;
    }

    public void setSupportButton(JButton supportButton) {
        this.supportButton = supportButton;
    }
}
