/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package titanic.gui;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Menes
 */
public class StartPanel extends javax.swing.JPanel {

    /**
     * Creates new form StartPanel
     */
    public StartPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        newProjectButton = new javax.swing.JButton();
        openProyectButton = new javax.swing.JButton();
        newUserButton = new javax.swing.JButton();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        setLayout(layout);

        newProjectButton.setText("Nuevo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(newProjectButton, gridBagConstraints);

        openProyectButton.setText("Abrir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        add(openProyectButton, gridBagConstraints);

        newUserButton.setText("Crear Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        add(newUserButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton newProjectButton;
    private javax.swing.JButton newUserButton;
    private javax.swing.JButton openProyectButton;
    // End of variables declaration//GEN-END:variables

    public JButton getNewProjectButton() {
        return newProjectButton;
    }

    public void setNewProjectButton(JButton newProjectButton) {
        this.newProjectButton = newProjectButton;
    }

    public JButton getNewUserButton() {
        return newUserButton;
    }

    public void setNewUserButton(JButton newUserButton) {
        this.newUserButton = newUserButton;
    }

    public JButton getOpenProyectButton() {
        return openProyectButton;
    }

    public void setOpenProyectButton(JButton openProyectButton) {
        this.openProyectButton = openProyectButton;
    }
}
